# CMake generated Testfile for 
# Source directory: /home/runner/work/Dmn/Dmn/test
# Build directory: /home/runner/work/Dmn/Dmn/_codeql_build_dir/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[dmn-test-async]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-async")
set_tests_properties([=[dmn-test-async]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-buffer]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-buffer")
set_tests_properties([=[dmn-test-buffer]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-buffer-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-buffer-2")
set_tests_properties([=[dmn-test-buffer-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-buffer-3]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-buffer-3")
set_tests_properties([=[dmn-test-buffer-3]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-buffer-4]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-buffer-4")
set_tests_properties([=[dmn-test-buffer-4]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-buffer-5]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-buffer-5")
set_tests_properties([=[dmn-test-buffer-5]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-1]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-1")
set_tests_properties([=[dmn-test-dmesg-1]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-2")
set_tests_properties([=[dmn-test-dmesg-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-3]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-3")
set_tests_properties([=[dmn-test-dmesg-3]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-5]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-5")
set_tests_properties([=[dmn-test-dmesg-5]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-6]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-6")
set_tests_properties([=[dmn-test-dmesg-6]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-7]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-7")
set_tests_properties([=[dmn-test-dmesg-7]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-8]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-8")
set_tests_properties([=[dmn-test-dmesg-8]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-9]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-9")
set_tests_properties([=[dmn-test-dmesg-9]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-10]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-10")
set_tests_properties([=[dmn-test-dmesg-10]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-11]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-11")
set_tests_properties([=[dmn-test-dmesg-11]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-1]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-1")
set_tests_properties([=[dmn-test-dmesgnet-1]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-2")
set_tests_properties([=[dmn-test-dmesgnet-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-3]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-3")
set_tests_properties([=[dmn-test-dmesgnet-3]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-4]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-4")
set_tests_properties([=[dmn-test-dmesgnet-4]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-5]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-5")
set_tests_properties([=[dmn-test-dmesgnet-5]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-6]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-6")
set_tests_properties([=[dmn-test-dmesgnet-6]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-pb]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-pb")
set_tests_properties([=[dmn-test-dmesg-pb]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesg-pb-util]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesg-pb-util")
set_tests_properties([=[dmn-test-dmesg-pb-util]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-io]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-io")
set_tests_properties([=[dmn-test-io]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-pipe]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-pipe")
set_tests_properties([=[dmn-test-pipe]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-pipe-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-pipe-2")
set_tests_properties([=[dmn-test-pipe-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-pipe-3]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-pipe-3")
set_tests_properties([=[dmn-test-pipe-3]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-pub-sub]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-pub-sub")
set_tests_properties([=[dmn-test-pub-sub]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-runtime]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-runtime")
set_tests_properties([=[dmn-test-runtime]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-runtime-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-runtime-2")
set_tests_properties([=[dmn-test-runtime-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-singleton]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-singleton")
set_tests_properties([=[dmn-test-singleton]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-socket]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-socket")
set_tests_properties([=[dmn-test-socket]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-teepipe]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-teepipe")
set_tests_properties([=[dmn-test-teepipe]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-timer]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-timer")
set_tests_properties([=[dmn-test-timer]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;9;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-with-kafka-1]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-with-kafka-1")
set_tests_properties([=[dmn-test-dmesgnet-with-kafka-1]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-with-kafka-2]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-with-kafka-2")
set_tests_properties([=[dmn-test-dmesgnet-with-kafka-2]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-with-kafka-3]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-with-kafka-3")
set_tests_properties([=[dmn-test-dmesgnet-with-kafka-3]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-with-kafka-4]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-with-kafka-4")
set_tests_properties([=[dmn-test-dmesgnet-with-kafka-4]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-dmesgnet-with-kafka-5]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-dmesgnet-with-kafka-5")
set_tests_properties([=[dmn-test-dmesgnet-with-kafka-5]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-kafka]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-kafka")
set_tests_properties([=[dmn-test-kafka]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
add_test([=[dmn-test-kafka-protobuf]=] "/home/runner/work/Dmn/Dmn/_codeql_build_dir/test/dmn-test-kafka-protobuf")
set_tests_properties([=[dmn-test-kafka-protobuf]=] PROPERTIES  LABELS "dmn" _BACKTRACE_TRIPLES "/home/runner/work/Dmn/Dmn/CMakeMacro.cmake;30;add_test;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;55;ADD_TEST_EXECUTABLE;/home/runner/work/Dmn/Dmn/test/CMakeLists.txt;0;")
