// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dmn-dmesg-body.proto
// Protobuf C++ Version: 6.30.0-rc1

#ifndef proto_2fdmn_2ddmesg_2dbody_2eproto_2epb_2eh
#define proto_2fdmn_2ddmesg_2dbody_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fdmn_2ddmesg_2dbody_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto;
}  // extern "C"
namespace Dmn {
enum DMesgStatePb : int;
extern const uint32_t DMesgStatePb_internal_data_[];
class DMesgBodyPb;
struct DMesgBodyPbDefaultTypeInternal;
extern DMesgBodyPbDefaultTypeInternal _DMesgBodyPb_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DMesgBodyPb_class_data_;
class DMesgSysNodePb;
struct DMesgSysNodePbDefaultTypeInternal;
extern DMesgSysNodePbDefaultTypeInternal _DMesgSysNodePb_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DMesgSysNodePb_class_data_;
class DMesgSysPb;
struct DMesgSysPbDefaultTypeInternal;
extern DMesgSysPbDefaultTypeInternal _DMesgSysPb_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DMesgSysPb_class_data_;
}  // namespace Dmn
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Dmn::DMesgStatePb_internal_data_>
    internal::EnumTraitsImpl::value<::Dmn::DMesgStatePb>;
}  // namespace protobuf
}  // namespace google

namespace Dmn {
enum DMesgStatePb : int {
  Invalid = 0,
  Initialized = 1,
  MasterPending = 2,
  Ready = 3,
  Destroyed = 15,
  DMesgStatePb_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DMesgStatePb_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t DMesgStatePb_internal_data_[];
inline constexpr DMesgStatePb DMesgStatePb_MIN =
    static_cast<DMesgStatePb>(0);
inline constexpr DMesgStatePb DMesgStatePb_MAX =
    static_cast<DMesgStatePb>(15);
inline bool DMesgStatePb_IsValid(int value) {
  return 0 <= value && value <= 15 && ((32783u >> value) & 1) != 0;
}
inline constexpr int DMesgStatePb_ARRAYSIZE = 15 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DMesgStatePb_descriptor();
template <typename T>
const std::string& DMesgStatePb_Name(T value) {
  static_assert(std::is_same<T, DMesgStatePb>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DMesgStatePb_Name().");
  return DMesgStatePb_Name(static_cast<DMesgStatePb>(value));
}
template <>
inline const std::string& DMesgStatePb_Name(DMesgStatePb value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DMesgStatePb_descriptor, 0, 15>(
      static_cast<int>(value));
}
inline bool DMesgStatePb_Parse(
    absl::string_view name, DMesgStatePb* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<DMesgStatePb>(DMesgStatePb_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class DMesgSysNodePb final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dmn.DMesgSysNodePb) */ {
 public:
  inline DMesgSysNodePb() : DMesgSysNodePb(nullptr) {}
  ~DMesgSysNodePb() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DMesgSysNodePb* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DMesgSysNodePb));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DMesgSysNodePb(::google::protobuf::internal::ConstantInitialized);

  inline DMesgSysNodePb(const DMesgSysNodePb& from) : DMesgSysNodePb(nullptr, from) {}
  inline DMesgSysNodePb(DMesgSysNodePb&& from) noexcept
      : DMesgSysNodePb(nullptr, std::move(from)) {}
  inline DMesgSysNodePb& operator=(const DMesgSysNodePb& from) {
    CopyFrom(from);
    return *this;
  }
  inline DMesgSysNodePb& operator=(DMesgSysNodePb&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DMesgSysNodePb& default_instance() {
    return *reinterpret_cast<const DMesgSysNodePb*>(
        &_DMesgSysNodePb_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DMesgSysNodePb& a, DMesgSysNodePb& b) { a.Swap(&b); }
  inline void Swap(DMesgSysNodePb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DMesgSysNodePb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DMesgSysNodePb* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DMesgSysNodePb>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DMesgSysNodePb& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DMesgSysNodePb& from) { DMesgSysNodePb::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DMesgSysNodePb* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dmn.DMesgSysNodePb"; }

 protected:
  explicit DMesgSysNodePb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DMesgSysNodePb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DMesgSysNodePb& from);
  DMesgSysNodePb(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DMesgSysNodePb&& from) noexcept
      : DMesgSysNodePb(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdentifierFieldNumber = 3,
    kMasterIdentifierFieldNumber = 5,
    kInitializedTimestampFieldNumber = 1,
    kUpdatedTimestampFieldNumber = 2,
    kStateFieldNumber = 4,
  };
  // string identifier = 3;
  void clear_identifier() ;
  const std::string& identifier() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_identifier(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_identifier();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_identifier();
  void set_allocated_identifier(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_identifier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_identifier(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_identifier();

  public:
  // string masterIdentifier = 5;
  void clear_masteridentifier() ;
  const std::string& masteridentifier() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_masteridentifier(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_masteridentifier();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_masteridentifier();
  void set_allocated_masteridentifier(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_masteridentifier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_masteridentifier(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_masteridentifier();

  public:
  // .google.protobuf.Timestamp initializedTimestamp = 1;
  bool has_initializedtimestamp() const;
  void clear_initializedtimestamp() ;
  const ::google::protobuf::Timestamp& initializedtimestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_initializedtimestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_initializedtimestamp();
  void set_allocated_initializedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_initializedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_initializedtimestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_initializedtimestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_initializedtimestamp();

  public:
  // .google.protobuf.Timestamp updatedTimestamp = 2;
  bool has_updatedtimestamp() const;
  void clear_updatedtimestamp() ;
  const ::google::protobuf::Timestamp& updatedtimestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_updatedtimestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_updatedtimestamp();
  void set_allocated_updatedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_updatedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_updatedtimestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_updatedtimestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_updatedtimestamp();

  public:
  // .Dmn.DMesgStatePb state = 4;
  void clear_state() ;
  ::Dmn::DMesgStatePb state() const;
  void set_state(::Dmn::DMesgStatePb value);

  private:
  ::Dmn::DMesgStatePb _internal_state() const;
  void _internal_set_state(::Dmn::DMesgStatePb value);

  public:
  // @@protoc_insertion_point(class_scope:Dmn.DMesgSysNodePb)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   2, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DMesgSysNodePb& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr identifier_;
    ::google::protobuf::internal::ArenaStringPtr masteridentifier_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE initializedtimestamp_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE updatedtimestamp_;
    int state_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DMesgSysNodePb_class_data_;
// -------------------------------------------------------------------

class DMesgSysPb final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dmn.DMesgSysPb) */ {
 public:
  inline DMesgSysPb() : DMesgSysPb(nullptr) {}
  ~DMesgSysPb() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DMesgSysPb* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DMesgSysPb));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DMesgSysPb(::google::protobuf::internal::ConstantInitialized);

  inline DMesgSysPb(const DMesgSysPb& from) : DMesgSysPb(nullptr, from) {}
  inline DMesgSysPb(DMesgSysPb&& from) noexcept
      : DMesgSysPb(nullptr, std::move(from)) {}
  inline DMesgSysPb& operator=(const DMesgSysPb& from) {
    CopyFrom(from);
    return *this;
  }
  inline DMesgSysPb& operator=(DMesgSysPb&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DMesgSysPb& default_instance() {
    return *reinterpret_cast<const DMesgSysPb*>(
        &_DMesgSysPb_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DMesgSysPb& a, DMesgSysPb& b) { a.Swap(&b); }
  inline void Swap(DMesgSysPb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DMesgSysPb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DMesgSysPb* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DMesgSysPb>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DMesgSysPb& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DMesgSysPb& from) { DMesgSysPb::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DMesgSysPb* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dmn.DMesgSysPb"; }

 protected:
  explicit DMesgSysPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DMesgSysPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DMesgSysPb& from);
  DMesgSysPb(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DMesgSysPb&& from) noexcept
      : DMesgSysPb(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNodeListFieldNumber = 5,
    kTimestampFieldNumber = 1,
    kSelfFieldNumber = 2,
  };
  // repeated .Dmn.DMesgSysNodePb nodeList = 5;
  int nodelist_size() const;
  private:
  int _internal_nodelist_size() const;

  public:
  void clear_nodelist() ;
  ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL mutable_nodelist(int index);
  ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>* PROTOBUF_NONNULL mutable_nodelist();

  private:
  const ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>& _internal_nodelist() const;
  ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>* PROTOBUF_NONNULL _internal_mutable_nodelist();
  public:
  const ::Dmn::DMesgSysNodePb& nodelist(int index) const;
  ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL add_nodelist();
  const ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>& nodelist() const;
  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_timestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // .Dmn.DMesgSysNodePb self = 2;
  bool has_self() const;
  void clear_self() ;
  const ::Dmn::DMesgSysNodePb& self() const;
  [[nodiscard]] ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE release_self();
  ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL mutable_self();
  void set_allocated_self(::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_self(::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE value);
  ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE unsafe_arena_release_self();

  private:
  const ::Dmn::DMesgSysNodePb& _internal_self() const;
  ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL _internal_mutable_self();

  public:
  // @@protoc_insertion_point(class_scope:Dmn.DMesgSysPb)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DMesgSysPb& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Dmn::DMesgSysNodePb > nodelist_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE timestamp_;
    ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE self_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DMesgSysPb_class_data_;
// -------------------------------------------------------------------

class DMesgBodyPb final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dmn.DMesgBodyPb) */ {
 public:
  inline DMesgBodyPb() : DMesgBodyPb(nullptr) {}
  ~DMesgBodyPb() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DMesgBodyPb* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DMesgBodyPb));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DMesgBodyPb(::google::protobuf::internal::ConstantInitialized);

  inline DMesgBodyPb(const DMesgBodyPb& from) : DMesgBodyPb(nullptr, from) {}
  inline DMesgBodyPb(DMesgBodyPb&& from) noexcept
      : DMesgBodyPb(nullptr, std::move(from)) {}
  inline DMesgBodyPb& operator=(const DMesgBodyPb& from) {
    CopyFrom(from);
    return *this;
  }
  inline DMesgBodyPb& operator=(DMesgBodyPb&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DMesgBodyPb& default_instance() {
    return *reinterpret_cast<const DMesgBodyPb*>(
        &_DMesgBodyPb_default_instance_);
  }
  enum BodyCase {
    kSys = 1,
    kMessage = 5,
    BODY_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DMesgBodyPb& a, DMesgBodyPb& b) { a.Swap(&b); }
  inline void Swap(DMesgBodyPb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DMesgBodyPb* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DMesgBodyPb* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DMesgBodyPb>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DMesgBodyPb& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DMesgBodyPb& from) { DMesgBodyPb::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DMesgBodyPb* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dmn.DMesgBodyPb"; }

 protected:
  explicit DMesgBodyPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DMesgBodyPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DMesgBodyPb& from);
  DMesgBodyPb(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DMesgBodyPb&& from) noexcept
      : DMesgBodyPb(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSysFieldNumber = 1,
    kMessageFieldNumber = 5,
  };
  // .Dmn.DMesgSysPb sys = 1;
  bool has_sys() const;
  private:
  bool _internal_has_sys() const;

  public:
  void clear_sys() ;
  const ::Dmn::DMesgSysPb& sys() const;
  [[nodiscard]] ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE release_sys();
  ::Dmn::DMesgSysPb* PROTOBUF_NONNULL mutable_sys();
  void set_allocated_sys(::Dmn::DMesgSysPb* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_sys(::Dmn::DMesgSysPb* PROTOBUF_NULLABLE value);
  ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE unsafe_arena_release_sys();

  private:
  const ::Dmn::DMesgSysPb& _internal_sys() const;
  ::Dmn::DMesgSysPb* PROTOBUF_NONNULL _internal_mutable_sys();

  public:
  // string message = 5;
  bool has_message() const;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  void clear_Body();
  BodyCase Body_case() const;
  // @@protoc_insertion_point(class_scope:Dmn.DMesgBodyPb)
 private:
  class _Internal;
  void set_has_sys();
  void set_has_message();
  inline bool has_Body() const;
  inline void clear_has_Body();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 2,
                                   1, 31,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DMesgBodyPb& from_msg);
    union BodyUnion {
      constexpr BodyUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE sys_;
      ::google::protobuf::internal::ArenaStringPtr message_;
    } Body_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DMesgBodyPb_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DMesgSysNodePb

// .google.protobuf.Timestamp initializedTimestamp = 1;
inline bool DMesgSysNodePb::has_initializedtimestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.initializedtimestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& DMesgSysNodePb::_internal_initializedtimestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.initializedtimestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& DMesgSysNodePb::initializedtimestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysNodePb.initializedTimestamp)
  return _internal_initializedtimestamp();
}
inline void DMesgSysNodePb::unsafe_arena_set_allocated_initializedtimestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.initializedtimestamp_);
  }
  _impl_.initializedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dmn.DMesgSysNodePb.initializedTimestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysNodePb::release_initializedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::Timestamp* released = _impl_.initializedtimestamp_;
  _impl_.initializedtimestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysNodePb::unsafe_arena_release_initializedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysNodePb.initializedTimestamp)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::google::protobuf::Timestamp* temp = _impl_.initializedtimestamp_;
  _impl_.initializedtimestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysNodePb::_internal_mutable_initializedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.initializedtimestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.initializedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.initializedtimestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysNodePb::mutable_initializedtimestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_initializedtimestamp();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysNodePb.initializedTimestamp)
  return _msg;
}
inline void DMesgSysNodePb::set_allocated_initializedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.initializedtimestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.initializedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysNodePb.initializedTimestamp)
}

// .google.protobuf.Timestamp updatedTimestamp = 2;
inline bool DMesgSysNodePb::has_updatedtimestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.updatedtimestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& DMesgSysNodePb::_internal_updatedtimestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.updatedtimestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& DMesgSysNodePb::updatedtimestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysNodePb.updatedTimestamp)
  return _internal_updatedtimestamp();
}
inline void DMesgSysNodePb::unsafe_arena_set_allocated_updatedtimestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.updatedtimestamp_);
  }
  _impl_.updatedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dmn.DMesgSysNodePb.updatedTimestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysNodePb::release_updatedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::google::protobuf::Timestamp* released = _impl_.updatedtimestamp_;
  _impl_.updatedtimestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysNodePb::unsafe_arena_release_updatedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysNodePb.updatedTimestamp)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::google::protobuf::Timestamp* temp = _impl_.updatedtimestamp_;
  _impl_.updatedtimestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysNodePb::_internal_mutable_updatedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.updatedtimestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.updatedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.updatedtimestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysNodePb::mutable_updatedtimestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_updatedtimestamp();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysNodePb.updatedTimestamp)
  return _msg;
}
inline void DMesgSysNodePb::set_allocated_updatedtimestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.updatedtimestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.updatedtimestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysNodePb.updatedTimestamp)
}

// string identifier = 3;
inline void DMesgSysNodePb::clear_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifier_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DMesgSysNodePb::identifier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysNodePb.identifier)
  return _internal_identifier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DMesgSysNodePb::set_identifier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.identifier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dmn.DMesgSysNodePb.identifier)
}
inline std::string* PROTOBUF_NONNULL DMesgSysNodePb::mutable_identifier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_identifier();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysNodePb.identifier)
  return _s;
}
inline const std::string& DMesgSysNodePb::_internal_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identifier_.Get();
}
inline void DMesgSysNodePb::_internal_set_identifier(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.identifier_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL DMesgSysNodePb::_internal_mutable_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.identifier_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE DMesgSysNodePb::release_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysNodePb.identifier)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.identifier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.identifier_.Set("", GetArena());
  }
  return released;
}
inline void DMesgSysNodePb::set_allocated_identifier(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.identifier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identifier_.IsDefault()) {
    _impl_.identifier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysNodePb.identifier)
}

// .Dmn.DMesgStatePb state = 4;
inline void DMesgSysNodePb::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::Dmn::DMesgStatePb DMesgSysNodePb::state() const {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysNodePb.state)
  return _internal_state();
}
inline void DMesgSysNodePb::set_state(::Dmn::DMesgStatePb value) {
  _internal_set_state(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:Dmn.DMesgSysNodePb.state)
}
inline ::Dmn::DMesgStatePb DMesgSysNodePb::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Dmn::DMesgStatePb>(_impl_.state_);
}
inline void DMesgSysNodePb::_internal_set_state(::Dmn::DMesgStatePb value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// string masterIdentifier = 5;
inline void DMesgSysNodePb::clear_masteridentifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.masteridentifier_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& DMesgSysNodePb::masteridentifier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysNodePb.masterIdentifier)
  return _internal_masteridentifier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DMesgSysNodePb::set_masteridentifier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.masteridentifier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dmn.DMesgSysNodePb.masterIdentifier)
}
inline std::string* PROTOBUF_NONNULL DMesgSysNodePb::mutable_masteridentifier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_masteridentifier();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysNodePb.masterIdentifier)
  return _s;
}
inline const std::string& DMesgSysNodePb::_internal_masteridentifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.masteridentifier_.Get();
}
inline void DMesgSysNodePb::_internal_set_masteridentifier(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.masteridentifier_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL DMesgSysNodePb::_internal_mutable_masteridentifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.masteridentifier_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE DMesgSysNodePb::release_masteridentifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysNodePb.masterIdentifier)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.masteridentifier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.masteridentifier_.Set("", GetArena());
  }
  return released;
}
inline void DMesgSysNodePb::set_allocated_masteridentifier(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.masteridentifier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.masteridentifier_.IsDefault()) {
    _impl_.masteridentifier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysNodePb.masterIdentifier)
}

// -------------------------------------------------------------------

// DMesgSysPb

// .google.protobuf.Timestamp timestamp = 1;
inline bool DMesgSysPb::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& DMesgSysPb::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& DMesgSysPb::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysPb.timestamp)
  return _internal_timestamp();
}
inline void DMesgSysPb::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dmn.DMesgSysPb.timestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysPb::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE DMesgSysPb::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysPb.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysPb::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL DMesgSysPb::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysPb.timestamp)
  return _msg;
}
inline void DMesgSysPb::set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysPb.timestamp)
}

// .Dmn.DMesgSysNodePb self = 2;
inline bool DMesgSysPb::has_self() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.self_ != nullptr);
  return value;
}
inline void DMesgSysPb::clear_self() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.self_ != nullptr) _impl_.self_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::Dmn::DMesgSysNodePb& DMesgSysPb::_internal_self() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Dmn::DMesgSysNodePb* p = _impl_.self_;
  return p != nullptr ? *p : reinterpret_cast<const ::Dmn::DMesgSysNodePb&>(::Dmn::_DMesgSysNodePb_default_instance_);
}
inline const ::Dmn::DMesgSysNodePb& DMesgSysPb::self() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysPb.self)
  return _internal_self();
}
inline void DMesgSysPb::unsafe_arena_set_allocated_self(
    ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.self_);
  }
  _impl_.self_ = reinterpret_cast<::Dmn::DMesgSysNodePb*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dmn.DMesgSysPb.self)
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE DMesgSysPb::release_self() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Dmn::DMesgSysNodePb* released = _impl_.self_;
  _impl_.self_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE DMesgSysPb::unsafe_arena_release_self() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgSysPb.self)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Dmn::DMesgSysNodePb* temp = _impl_.self_;
  _impl_.self_ = nullptr;
  return temp;
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL DMesgSysPb::_internal_mutable_self() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.self_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Dmn::DMesgSysNodePb>(GetArena());
    _impl_.self_ = reinterpret_cast<::Dmn::DMesgSysNodePb*>(p);
  }
  return _impl_.self_;
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL DMesgSysPb::mutable_self()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Dmn::DMesgSysNodePb* _msg = _internal_mutable_self();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysPb.self)
  return _msg;
}
inline void DMesgSysPb::set_allocated_self(::Dmn::DMesgSysNodePb* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.self_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.self_ = reinterpret_cast<::Dmn::DMesgSysNodePb*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgSysPb.self)
}

// repeated .Dmn.DMesgSysNodePb nodeList = 5;
inline int DMesgSysPb::_internal_nodelist_size() const {
  return _internal_nodelist().size();
}
inline int DMesgSysPb::nodelist_size() const {
  return _internal_nodelist_size();
}
inline void DMesgSysPb::clear_nodelist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodelist_.Clear();
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL DMesgSysPb::mutable_nodelist(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgSysPb.nodeList)
  return _internal_mutable_nodelist()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>* PROTOBUF_NONNULL DMesgSysPb::mutable_nodelist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Dmn.DMesgSysPb.nodeList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_nodelist();
}
inline const ::Dmn::DMesgSysNodePb& DMesgSysPb::nodelist(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgSysPb.nodeList)
  return _internal_nodelist().Get(index);
}
inline ::Dmn::DMesgSysNodePb* PROTOBUF_NONNULL DMesgSysPb::add_nodelist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Dmn::DMesgSysNodePb* _add = _internal_mutable_nodelist()->Add();
  // @@protoc_insertion_point(field_add:Dmn.DMesgSysPb.nodeList)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>& DMesgSysPb::nodelist() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Dmn.DMesgSysPb.nodeList)
  return _internal_nodelist();
}
inline const ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>&
DMesgSysPb::_internal_nodelist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodelist_;
}
inline ::google::protobuf::RepeatedPtrField<::Dmn::DMesgSysNodePb>* PROTOBUF_NONNULL
DMesgSysPb::_internal_mutable_nodelist() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.nodelist_;
}

// -------------------------------------------------------------------

// DMesgBodyPb

// .Dmn.DMesgSysPb sys = 1;
inline bool DMesgBodyPb::has_sys() const {
  return Body_case() == kSys;
}
inline bool DMesgBodyPb::_internal_has_sys() const {
  return Body_case() == kSys;
}
inline void DMesgBodyPb::set_has_sys() {
  _impl_._oneof_case_[0] = kSys;
}
inline void DMesgBodyPb::clear_sys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Body_case() == kSys) {
    if (GetArena() == nullptr) {
      delete _impl_.Body_.sys_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Body_.sys_);
    }
    clear_has_Body();
  }
}
inline ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE DMesgBodyPb::release_sys() {
  // @@protoc_insertion_point(field_release:Dmn.DMesgBodyPb.sys)
  if (Body_case() == kSys) {
    clear_has_Body();
    auto* temp = _impl_.Body_.sys_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.Body_.sys_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Dmn::DMesgSysPb& DMesgBodyPb::_internal_sys() const {
  return Body_case() == kSys ? *_impl_.Body_.sys_ : reinterpret_cast<::Dmn::DMesgSysPb&>(::Dmn::_DMesgSysPb_default_instance_);
}
inline const ::Dmn::DMesgSysPb& DMesgBodyPb::sys() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgBodyPb.sys)
  return _internal_sys();
}
inline ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE DMesgBodyPb::unsafe_arena_release_sys() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Dmn.DMesgBodyPb.sys)
  if (Body_case() == kSys) {
    clear_has_Body();
    auto* temp = _impl_.Body_.sys_;
    _impl_.Body_.sys_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void DMesgBodyPb::unsafe_arena_set_allocated_sys(
    ::Dmn::DMesgSysPb* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_Body();
  if (value) {
    set_has_sys();
    _impl_.Body_.sys_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dmn.DMesgBodyPb.sys)
}
inline ::Dmn::DMesgSysPb* PROTOBUF_NONNULL DMesgBodyPb::_internal_mutable_sys() {
  if (Body_case() != kSys) {
    clear_Body();
    set_has_sys();
    _impl_.Body_.sys_ = 
        ::google::protobuf::Message::DefaultConstruct<::Dmn::DMesgSysPb>(GetArena());
  }
  return _impl_.Body_.sys_;
}
inline ::Dmn::DMesgSysPb* PROTOBUF_NONNULL DMesgBodyPb::mutable_sys()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Dmn::DMesgSysPb* _msg = _internal_mutable_sys();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgBodyPb.sys)
  return _msg;
}

// string message = 5;
inline bool DMesgBodyPb::has_message() const {
  return Body_case() == kMessage;
}
inline void DMesgBodyPb::set_has_message() {
  _impl_._oneof_case_[0] = kMessage;
}
inline void DMesgBodyPb::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Body_case() == kMessage) {
    _impl_.Body_.message_.Destroy();
    clear_has_Body();
  }
}
inline const std::string& DMesgBodyPb::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dmn.DMesgBodyPb.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DMesgBodyPb::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Body_case() != kMessage) {
    clear_Body();

    set_has_message();
    _impl_.Body_.message_.InitDefault();
  }
  _impl_.Body_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dmn.DMesgBodyPb.message)
}
inline std::string* PROTOBUF_NONNULL DMesgBodyPb::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:Dmn.DMesgBodyPb.message)
  return _s;
}
inline const std::string& DMesgBodyPb::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (Body_case() != kMessage) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.Body_.message_.Get();
}
inline void DMesgBodyPb::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Body_case() != kMessage) {
    clear_Body();

    set_has_message();
    _impl_.Body_.message_.InitDefault();
  }
  _impl_.Body_.message_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL DMesgBodyPb::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Body_case() != kMessage) {
    clear_Body();

    set_has_message();
    _impl_.Body_.message_.InitDefault();
  }
  return _impl_.Body_.message_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE DMesgBodyPb::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dmn.DMesgBodyPb.message)
  if (Body_case() != kMessage) {
    return nullptr;
  }
  clear_has_Body();
  return _impl_.Body_.message_.Release();
}
inline void DMesgBodyPb::set_allocated_message(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_Body()) {
    clear_Body();
  }
  if (value != nullptr) {
    set_has_message();
    _impl_.Body_.message_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgBodyPb.message)
}

inline bool DMesgBodyPb::has_Body() const {
  return Body_case() != BODY_NOT_SET;
}
inline void DMesgBodyPb::clear_has_Body() {
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}
inline DMesgBodyPb::BodyCase DMesgBodyPb::Body_case() const {
  return DMesgBodyPb::BodyCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Dmn


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Dmn::DMesgStatePb> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Dmn::DMesgStatePb>() {
  return ::Dmn::DMesgStatePb_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fdmn_2ddmesg_2dbody_2eproto_2epb_2eh
