// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dmn-dmesg-body.proto
// Protobuf C++ Version: 6.30.0-rc1

#include "proto/dmn-dmesg-body.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Dmn {

inline constexpr DMesgSysNodePb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        identifier_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        masteridentifier_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        initializedtimestamp_{nullptr},
        updatedtimestamp_{nullptr},
        state_{static_cast< ::Dmn::DMesgStatePb >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR DMesgSysNodePb::DMesgSysNodePb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DMesgSysNodePb_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DMesgSysNodePbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DMesgSysNodePbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DMesgSysNodePbDefaultTypeInternal() {}
  union {
    DMesgSysNodePb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DMesgSysNodePbDefaultTypeInternal _DMesgSysNodePb_default_instance_;

inline constexpr DMesgSysPb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nodelist_{},
        timestamp_{nullptr},
        self_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR DMesgSysPb::DMesgSysPb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DMesgSysPb_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DMesgSysPbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DMesgSysPbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DMesgSysPbDefaultTypeInternal() {}
  union {
    DMesgSysPb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DMesgSysPbDefaultTypeInternal _DMesgSysPb_default_instance_;

inline constexpr DMesgBodyPb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : Body_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR DMesgBodyPb::DMesgBodyPb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DMesgBodyPb_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DMesgBodyPbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DMesgBodyPbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DMesgBodyPbDefaultTypeInternal() {}
  union {
    DMesgBodyPb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DMesgBodyPbDefaultTypeInternal _DMesgBodyPb_default_instance_;
}  // namespace Dmn
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dbody_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fdmn_2ddmesg_2dbody_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_.initializedtimestamp_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_.updatedtimestamp_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_.identifier_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysNodePb, _impl_.masteridentifier_),
        2,
        3,
        0,
        4,
        1,
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysPb, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysPb, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysPb, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysPb, _impl_.self_),
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgSysPb, _impl_.nodelist_),
        0,
        1,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgBodyPb, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgBodyPb, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Dmn::DMesgBodyPb, _impl_.Body_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 13, -1, sizeof(::Dmn::DMesgSysNodePb)},
        {18, 29, -1, sizeof(::Dmn::DMesgSysPb)},
        {32, -1, -1, sizeof(::Dmn::DMesgBodyPb)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Dmn::_DMesgSysNodePb_default_instance_._instance,
    &::Dmn::_DMesgSysPb_default_instance_._instance,
    &::Dmn::_DMesgBodyPb_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fdmn_2ddmesg_2dbody_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032proto/dmn-dmesg-body.proto\022\003Dmn\032\037googl"
    "e/protobuf/timestamp.proto\"\320\001\n\016DMesgSysN"
    "odePb\0228\n\024initializedTimestamp\030\001 \001(\0132\032.go"
    "ogle.protobuf.Timestamp\0224\n\020updatedTimest"
    "amp\030\002 \001(\0132\032.google.protobuf.Timestamp\022\022\n"
    "\nidentifier\030\003 \001(\t\022 \n\005state\030\004 \001(\0162\021.Dmn.D"
    "MesgStatePb\022\030\n\020masterIdentifier\030\005 \001(\t\"\205\001"
    "\n\nDMesgSysPb\022-\n\ttimestamp\030\001 \001(\0132\032.google"
    ".protobuf.Timestamp\022!\n\004self\030\002 \001(\0132\023.Dmn."
    "DMesgSysNodePb\022%\n\010nodeList\030\005 \003(\0132\023.Dmn.D"
    "MesgSysNodePb\"H\n\013DMesgBodyPb\022\036\n\003sys\030\001 \001("
    "\0132\017.Dmn.DMesgSysPbH\000\022\021\n\007message\030\005 \001(\tH\000B"
    "\006\n\004Body*Y\n\014DMesgStatePb\022\013\n\007Invalid\020\000\022\017\n\013"
    "Initialized\020\001\022\021\n\rMasterPending\020\002\022\t\n\005Read"
    "y\020\003\022\r\n\tDestroyed\020\017b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto = {
    false,
    false,
    586,
    descriptor_table_protodef_proto_2fdmn_2ddmesg_2dbody_2eproto,
    "proto/dmn-dmesg-body.proto",
    &descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto_once,
    descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_proto_2fdmn_2ddmesg_2dbody_2eproto::offsets,
    file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dbody_2eproto,
    file_level_service_descriptors_proto_2fdmn_2ddmesg_2dbody_2eproto,
};
namespace Dmn {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DMesgStatePb_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto);
  return file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dbody_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DMesgStatePb_internal_data_[] = {
    262144u, 32u, 2048u, };
// ===================================================================

class DMesgSysNodePb::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DMesgSysNodePb>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_._has_bits_);
};

void DMesgSysNodePb::clear_initializedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.initializedtimestamp_ != nullptr) _impl_.initializedtimestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void DMesgSysNodePb::clear_updatedtimestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.updatedtimestamp_ != nullptr) _impl_.updatedtimestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
DMesgSysNodePb::DMesgSysNodePb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgSysNodePb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Dmn.DMesgSysNodePb)
}
PROTOBUF_NDEBUG_INLINE DMesgSysNodePb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Dmn::DMesgSysNodePb& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        identifier_(arena, from.identifier_),
        masteridentifier_(arena, from.masteridentifier_) {}

DMesgSysNodePb::DMesgSysNodePb(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DMesgSysNodePb& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgSysNodePb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DMesgSysNodePb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.initializedtimestamp_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.initializedtimestamp_)
                : nullptr;
  _impl_.updatedtimestamp_ = ((cached_has_bits & 0x00000008u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.updatedtimestamp_)
                : nullptr;
  _impl_.state_ = from._impl_.state_;

  // @@protoc_insertion_point(copy_constructor:Dmn.DMesgSysNodePb)
}
PROTOBUF_NDEBUG_INLINE DMesgSysNodePb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        identifier_(arena),
        masteridentifier_(arena) {}

inline void DMesgSysNodePb::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, initializedtimestamp_),
           0,
           offsetof(Impl_, state_) -
               offsetof(Impl_, initializedtimestamp_) +
               sizeof(Impl_::state_));
}
DMesgSysNodePb::~DMesgSysNodePb() {
  // @@protoc_insertion_point(destructor:Dmn.DMesgSysNodePb)
  SharedDtor(*this);
}
inline void DMesgSysNodePb::SharedDtor(MessageLite& self) {
  DMesgSysNodePb& this_ = static_cast<DMesgSysNodePb&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.identifier_.Destroy();
  this_._impl_.masteridentifier_.Destroy();
  delete this_._impl_.initializedtimestamp_;
  delete this_._impl_.updatedtimestamp_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DMesgSysNodePb::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DMesgSysNodePb(arena);
}
constexpr auto DMesgSysNodePb::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DMesgSysNodePb),
                                            alignof(DMesgSysNodePb));
}
constexpr auto DMesgSysNodePb::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DMesgSysNodePb_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DMesgSysNodePb::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DMesgSysNodePb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DMesgSysNodePb::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DMesgSysNodePb>(), &DMesgSysNodePb::ByteSizeLong,
              &DMesgSysNodePb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_._cached_size_),
          false,
      },
      &DMesgSysNodePb::kDescriptorMethods,
      &descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        DMesgSysNodePb_class_data_ =
            DMesgSysNodePb::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL DMesgSysNodePb::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DMesgSysNodePb_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DMesgSysNodePb_class_data_.tc_table);
  return DMesgSysNodePb_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 53, 2>
DMesgSysNodePb::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DMesgSysNodePb_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Dmn::DMesgSysNodePb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .google.protobuf.Timestamp initializedTimestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 2, 0, PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.initializedtimestamp_)}},
    // .google.protobuf.Timestamp updatedTimestamp = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 1, PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.updatedtimestamp_)}},
    // string identifier = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.identifier_)}},
    // .Dmn.DMesgStatePb state = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DMesgSysNodePb, _impl_.state_), 4>(),
     {32, 4, 0, PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.state_)}},
    // string masterIdentifier = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 1, 0, PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.masteridentifier_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp initializedTimestamp = 1;
    {PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.initializedtimestamp_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp updatedTimestamp = 2;
    {PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.updatedtimestamp_), _Internal::kHasBitsOffset + 3, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string identifier = 3;
    {PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.identifier_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Dmn.DMesgStatePb state = 4;
    {PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.state_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string masterIdentifier = 5;
    {PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.masteridentifier_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }},
  {{
    "\22\0\0\12\0\20\0\0"
    "Dmn.DMesgSysNodePb"
    "identifier"
    "masterIdentifier"
  }},
};
PROTOBUF_NOINLINE void DMesgSysNodePb::Clear() {
// @@protoc_insertion_point(message_clear_start:Dmn.DMesgSysNodePb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.identifier_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.masteridentifier_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.initializedtimestamp_ != nullptr);
      _impl_.initializedtimestamp_->Clear();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(_impl_.updatedtimestamp_ != nullptr);
      _impl_.updatedtimestamp_->Clear();
    }
  }
  _impl_.state_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DMesgSysNodePb::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DMesgSysNodePb& this_ = static_cast<const DMesgSysNodePb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DMesgSysNodePb::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DMesgSysNodePb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Dmn.DMesgSysNodePb)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .google.protobuf.Timestamp initializedTimestamp = 1;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.initializedtimestamp_, this_._impl_.initializedtimestamp_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.Timestamp updatedTimestamp = 2;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.updatedtimestamp_, this_._impl_.updatedtimestamp_->GetCachedSize(), target,
        stream);
  }

  // string identifier = 3;
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!this_._internal_identifier().empty()) {
      const std::string& _s = this_._internal_identifier();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Dmn.DMesgSysNodePb.identifier");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // .Dmn.DMesgStatePb state = 4;
  if ((cached_has_bits & 0x00000010u) != 0) {
    if (this_._internal_state() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_state(), target);
    }
  }

  // string masterIdentifier = 5;
  if ((cached_has_bits & 0x00000002u) != 0) {
    if (!this_._internal_masteridentifier().empty()) {
      const std::string& _s = this_._internal_masteridentifier();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Dmn.DMesgSysNodePb.masterIdentifier");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Dmn.DMesgSysNodePb)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DMesgSysNodePb::ByteSizeLong(const MessageLite& base) {
  const DMesgSysNodePb& this_ = static_cast<const DMesgSysNodePb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DMesgSysNodePb::ByteSizeLong() const {
  const DMesgSysNodePb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Dmn.DMesgSysNodePb)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // string identifier = 3;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_identifier().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_identifier());
      }
    }
    // string masterIdentifier = 5;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_masteridentifier().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_masteridentifier());
      }
    }
    // .google.protobuf.Timestamp initializedTimestamp = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.initializedtimestamp_);
    }
    // .google.protobuf.Timestamp updatedTimestamp = 2;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.updatedtimestamp_);
    }
    // .Dmn.DMesgStatePb state = 4;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_state() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_state());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DMesgSysNodePb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DMesgSysNodePb*>(&to_msg);
  auto& from = static_cast<const DMesgSysNodePb&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Dmn.DMesgSysNodePb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_identifier().empty()) {
        _this->_internal_set_identifier(from._internal_identifier());
      } else {
        if (_this->_impl_.identifier_.IsDefault()) {
          _this->_internal_set_identifier("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_masteridentifier().empty()) {
        _this->_internal_set_masteridentifier(from._internal_masteridentifier());
      } else {
        if (_this->_impl_.masteridentifier_.IsDefault()) {
          _this->_internal_set_masteridentifier("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.initializedtimestamp_ != nullptr);
      if (_this->_impl_.initializedtimestamp_ == nullptr) {
        _this->_impl_.initializedtimestamp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.initializedtimestamp_);
      } else {
        _this->_impl_.initializedtimestamp_->MergeFrom(*from._impl_.initializedtimestamp_);
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(from._impl_.updatedtimestamp_ != nullptr);
      if (_this->_impl_.updatedtimestamp_ == nullptr) {
        _this->_impl_.updatedtimestamp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.updatedtimestamp_);
      } else {
        _this->_impl_.updatedtimestamp_->MergeFrom(*from._impl_.updatedtimestamp_);
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_state() != 0) {
        _this->_impl_.state_ = from._impl_.state_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DMesgSysNodePb::CopyFrom(const DMesgSysNodePb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Dmn.DMesgSysNodePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DMesgSysNodePb::InternalSwap(DMesgSysNodePb* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.identifier_, &other->_impl_.identifier_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.masteridentifier_, &other->_impl_.masteridentifier_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.state_)
      + sizeof(DMesgSysNodePb::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(DMesgSysNodePb, _impl_.initializedtimestamp_)>(
          reinterpret_cast<char*>(&_impl_.initializedtimestamp_),
          reinterpret_cast<char*>(&other->_impl_.initializedtimestamp_));
}

::google::protobuf::Metadata DMesgSysNodePb::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DMesgSysPb::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DMesgSysPb>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_._has_bits_);
};

void DMesgSysPb::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
DMesgSysPb::DMesgSysPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgSysPb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Dmn.DMesgSysPb)
}
PROTOBUF_NDEBUG_INLINE DMesgSysPb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Dmn::DMesgSysPb& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nodelist_{visibility, arena, from.nodelist_} {}

DMesgSysPb::DMesgSysPb(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DMesgSysPb& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgSysPb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DMesgSysPb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timestamp_)
                : nullptr;
  _impl_.self_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.self_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:Dmn.DMesgSysPb)
}
PROTOBUF_NDEBUG_INLINE DMesgSysPb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nodelist_{visibility, arena} {}

inline void DMesgSysPb::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, self_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::self_));
}
DMesgSysPb::~DMesgSysPb() {
  // @@protoc_insertion_point(destructor:Dmn.DMesgSysPb)
  SharedDtor(*this);
}
inline void DMesgSysPb::SharedDtor(MessageLite& self) {
  DMesgSysPb& this_ = static_cast<DMesgSysPb&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.timestamp_;
  delete this_._impl_.self_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL DMesgSysPb::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DMesgSysPb(arena);
}
constexpr auto DMesgSysPb::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.nodelist_) +
          decltype(DMesgSysPb::_impl_.nodelist_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DMesgSysPb), alignof(DMesgSysPb), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DMesgSysPb::PlacementNew_,
                                 sizeof(DMesgSysPb),
                                 alignof(DMesgSysPb));
  }
}
constexpr auto DMesgSysPb::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DMesgSysPb_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DMesgSysPb::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DMesgSysPb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DMesgSysPb::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DMesgSysPb>(), &DMesgSysPb::ByteSizeLong,
              &DMesgSysPb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_._cached_size_),
          false,
      },
      &DMesgSysPb::kDescriptorMethods,
      &descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        DMesgSysPb_class_data_ =
            DMesgSysPb::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL DMesgSysPb::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DMesgSysPb_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DMesgSysPb_class_data_.tc_table);
  return DMesgSysPb_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 3, 3, 0, 2>
DMesgSysPb::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_._has_bits_),
    0, // no _extensions_
    5, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967276,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DMesgSysPb_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Dmn::DMesgSysPb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Dmn.DMesgSysNodePb self = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.self_)}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Dmn.DMesgSysNodePb self = 2;
    {PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.self_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .Dmn.DMesgSysNodePb nodeList = 5;
    {PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.nodelist_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::Dmn::DMesgSysNodePb>()},
      {::_pbi::TcParser::GetTable<::Dmn::DMesgSysNodePb>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void DMesgSysPb::Clear() {
// @@protoc_insertion_point(message_clear_start:Dmn.DMesgSysPb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodelist_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.self_ != nullptr);
      _impl_.self_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DMesgSysPb::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DMesgSysPb& this_ = static_cast<const DMesgSysPb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DMesgSysPb::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DMesgSysPb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Dmn.DMesgSysPb)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .google.protobuf.Timestamp timestamp = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
        stream);
  }

  // .Dmn.DMesgSysNodePb self = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.self_, this_._impl_.self_->GetCachedSize(), target,
        stream);
  }

  // repeated .Dmn.DMesgSysNodePb nodeList = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_nodelist_size());
       i < n; i++) {
    const auto& repfield = this_._internal_nodelist().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Dmn.DMesgSysPb)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DMesgSysPb::ByteSizeLong(const MessageLite& base) {
  const DMesgSysPb& this_ = static_cast<const DMesgSysPb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DMesgSysPb::ByteSizeLong() const {
  const DMesgSysPb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Dmn.DMesgSysPb)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .Dmn.DMesgSysNodePb nodeList = 5;
    {
      total_size += 1UL * this_._internal_nodelist_size();
      for (const auto& msg : this_._internal_nodelist()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .google.protobuf.Timestamp timestamp = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
    }
    // .Dmn.DMesgSysNodePb self = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.self_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DMesgSysPb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DMesgSysPb*>(&to_msg);
  auto& from = static_cast<const DMesgSysPb&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Dmn.DMesgSysPb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_nodelist()->MergeFrom(
      from._internal_nodelist());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
      if (_this->_impl_.timestamp_ == nullptr) {
        _this->_impl_.timestamp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timestamp_);
      } else {
        _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.self_ != nullptr);
      if (_this->_impl_.self_ == nullptr) {
        _this->_impl_.self_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.self_);
      } else {
        _this->_impl_.self_->MergeFrom(*from._impl_.self_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DMesgSysPb::CopyFrom(const DMesgSysPb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Dmn.DMesgSysPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DMesgSysPb::InternalSwap(DMesgSysPb* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.nodelist_.InternalSwap(&other->_impl_.nodelist_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.self_)
      + sizeof(DMesgSysPb::_impl_.self_)
      - PROTOBUF_FIELD_OFFSET(DMesgSysPb, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata DMesgSysPb::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DMesgBodyPb::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Dmn::DMesgBodyPb, _impl_._oneof_case_);
};

void DMesgBodyPb::set_allocated_sys(::Dmn::DMesgSysPb* PROTOBUF_NULLABLE sys) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Body();
  if (sys) {
    ::google::protobuf::Arena* submessage_arena = sys->GetArena();
    if (message_arena != submessage_arena) {
      sys = ::google::protobuf::internal::GetOwnedMessage(message_arena, sys, submessage_arena);
    }
    set_has_sys();
    _impl_.Body_.sys_ = sys;
  }
  // @@protoc_insertion_point(field_set_allocated:Dmn.DMesgBodyPb.sys)
}
DMesgBodyPb::DMesgBodyPb(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgBodyPb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Dmn.DMesgBodyPb)
}
PROTOBUF_NDEBUG_INLINE DMesgBodyPb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::Dmn::DMesgBodyPb& from_msg)
      : Body_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

DMesgBodyPb::DMesgBodyPb(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DMesgBodyPb& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DMesgBodyPb_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DMesgBodyPb* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (Body_case()) {
    case BODY_NOT_SET:
      break;
      case kSys:
        _impl_.Body_.sys_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Body_.sys_);
        break;
      case kMessage:
        new (&_impl_.Body_.message_) decltype(_impl_.Body_.message_){arena, from._impl_.Body_.message_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Dmn.DMesgBodyPb)
}
PROTOBUF_NDEBUG_INLINE DMesgBodyPb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : Body_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void DMesgBodyPb::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DMesgBodyPb::~DMesgBodyPb() {
  // @@protoc_insertion_point(destructor:Dmn.DMesgBodyPb)
  SharedDtor(*this);
}
inline void DMesgBodyPb::SharedDtor(MessageLite& self) {
  DMesgBodyPb& this_ = static_cast<DMesgBodyPb&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_Body()) {
    this_.clear_Body();
  }
  this_._impl_.~Impl_();
}

void DMesgBodyPb::clear_Body() {
// @@protoc_insertion_point(one_of_clear_start:Dmn.DMesgBodyPb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (Body_case()) {
    case kSys: {
      if (GetArena() == nullptr) {
        delete _impl_.Body_.sys_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Body_.sys_);
      }
      break;
    }
    case kMessage: {
      _impl_.Body_.message_.Destroy();
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


inline void* PROTOBUF_NONNULL DMesgBodyPb::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DMesgBodyPb(arena);
}
constexpr auto DMesgBodyPb::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DMesgBodyPb),
                                            alignof(DMesgBodyPb));
}
constexpr auto DMesgBodyPb::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DMesgBodyPb_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DMesgBodyPb::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DMesgBodyPb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DMesgBodyPb::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DMesgBodyPb>(), &DMesgBodyPb::ByteSizeLong,
              &DMesgBodyPb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DMesgBodyPb, _impl_._cached_size_),
          false,
      },
      &DMesgBodyPb::kDescriptorMethods,
      &descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        DMesgBodyPb_class_data_ =
            DMesgBodyPb::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL DMesgBodyPb::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DMesgBodyPb_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DMesgBodyPb_class_data_.tc_table);
  return DMesgBodyPb_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 31, 2>
DMesgBodyPb::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967278,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DMesgBodyPb_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Dmn::DMesgBodyPb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Dmn.DMesgSysPb sys = 1;
    {PROTOBUF_FIELD_OFFSET(DMesgBodyPb, _impl_.Body_.sys_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // string message = 5;
    {PROTOBUF_FIELD_OFFSET(DMesgBodyPb, _impl_.Body_.message_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Dmn::DMesgSysPb>()},
  }},
  {{
    "\17\0\7\0\0\0\0\0"
    "Dmn.DMesgBodyPb"
    "message"
  }},
};
PROTOBUF_NOINLINE void DMesgBodyPb::Clear() {
// @@protoc_insertion_point(message_clear_start:Dmn.DMesgBodyPb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Body();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DMesgBodyPb::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DMesgBodyPb& this_ = static_cast<const DMesgBodyPb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DMesgBodyPb::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DMesgBodyPb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Dmn.DMesgBodyPb)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.Body_case()) {
    case kSys: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.Body_.sys_, this_._impl_.Body_.sys_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMessage: {
      const std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Dmn.DMesgBodyPb.message");
      target = stream->WriteStringMaybeAliased(5, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Dmn.DMesgBodyPb)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DMesgBodyPb::ByteSizeLong(const MessageLite& base) {
  const DMesgBodyPb& this_ = static_cast<const DMesgBodyPb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DMesgBodyPb::ByteSizeLong() const {
  const DMesgBodyPb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Dmn.DMesgBodyPb)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.Body_case()) {
    // .Dmn.DMesgSysPb sys = 1;
    case kSys: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Body_.sys_);
      break;
    }
    // string message = 5;
    case kMessage: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_message());
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DMesgBodyPb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DMesgBodyPb*>(&to_msg);
  auto& from = static_cast<const DMesgBodyPb&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Dmn.DMesgBodyPb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_Body();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSys: {
        if (oneof_needs_init) {
          _this->_impl_.Body_.sys_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Body_.sys_);
        } else {
          _this->_impl_.Body_.sys_->MergeFrom(*from._impl_.Body_.sys_);
        }
        break;
      }
      case kMessage: {
        if (oneof_needs_init) {
          _this->_impl_.Body_.message_.InitDefault();
        }
        _this->_impl_.Body_.message_.Set(from._internal_message(), arena);
        break;
      }
      case BODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DMesgBodyPb::CopyFrom(const DMesgBodyPb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Dmn.DMesgBodyPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DMesgBodyPb::InternalSwap(DMesgBodyPb* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.Body_, other->_impl_.Body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata DMesgBodyPb::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Dmn
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fdmn_2ddmesg_2dbody_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
