// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dmn-dmesg-type.proto
// Protobuf C++ Version: 6.30.0-rc1

#include "proto/dmn-dmesg-type.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Dmn {
}  // namespace Dmn
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dtype_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fdmn_2ddmesg_2dtype_2eproto = nullptr;
const ::uint32_t TableStruct_proto_2fdmn_2ddmesg_2dtype_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_proto_2fdmn_2ddmesg_2dtype_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032proto/dmn-dmesg-type.proto\022\003Dmn*0\n\013DMe"
    "sgTypePb\022\013\n\007INVALID\020\000\022\007\n\003sys\020\001\022\013\n\007messag"
    "e\020\005b\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fdmn_2ddmesg_2dtype_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fdmn_2ddmesg_2dtype_2eproto = {
    false,
    false,
    91,
    descriptor_table_protodef_proto_2fdmn_2ddmesg_2dtype_2eproto,
    "proto/dmn-dmesg-type.proto",
    &descriptor_table_proto_2fdmn_2ddmesg_2dtype_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_proto_2fdmn_2ddmesg_2dtype_2eproto::offsets,
    file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dtype_2eproto,
    file_level_service_descriptors_proto_2fdmn_2ddmesg_2dtype_2eproto,
};
namespace Dmn {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DMesgTypePb_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fdmn_2ddmesg_2dtype_2eproto);
  return file_level_enum_descriptors_proto_2fdmn_2ddmesg_2dtype_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DMesgTypePb_internal_data_[] = {
    131072u, 32u, 8u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace Dmn
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fdmn_2ddmesg_2dtype_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
