name: CMake on a single platform

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dmn .

      - name: Run container tests
        run: docker run --rm dmn


