name: build and run on linux platform

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'For linux build and test run'
        required: false
        default: 'Manual run on linux'

env:
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  linux-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dmn .

      - name: Run container tests
        run: docker run --rm dmn


