# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake with Valgrind on a single platform

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'For valgrind memory check'
        required: false
        default: 'Manual update'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dmn .

      - name: Run container tests
        run: docker run --rm -e CTEST_LABEL=valgrind dmn


